version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    image: nginx:1.13.10
    volumes:
      - ./:/code
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 127.0.0.1:80:80

  php.symfony:
    container_name: php.symfony
    image: php.symfony
    environment:
      - APP_ENV=prod
      - APP_SECRET=460e7ab843a2e9a80801934185be6022b6e1cdfb9a510c08debee23a9e73deb6
      - DATABASE_URL=mysql://root:OjitmawfOb7GriGros9@mysql.symfony:3306/symfony
    volumes:
      - ./:/code

  mysql.symfony:
    container_name: mysql.symfony
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=OjitmawfOb7GriGros9
    volumes:
      - ./.docker/mysql-data/:/var/lib/mysql

  frontend.symfony:
    container_name: frontend.symfony
    image: frontend.symfony
    volumes:
      - ./:/code
    ports:
      - 127.0.0.1:9500:9500
    extra_hosts:
     - "symfony.local:0.0.0.0"
