#index:
#    path: /
<<<<<<< HEAD
#    controller: App\Controller\DefaultController::index
=======
#    controller: App\Controller\HomeController::index
>>>>>>> 26ba564ce16e728a7cc20cf79ffc26bbfab69210
